name: ease_state_helper
description: A simple Flutter state management helper that makes using Flutter's internal state management easier.
version: 1.0.0
homepage: https://github.com/y3l1n4ung/ease
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
