name: ease_state_helper
description: Simple Flutter state management helper with InheritedWidget
version: 1.0.0
homepage: https://github.com/b14ckc0d3/ease
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
