name: ease_annotation
description: Annotations for ease state management helper
version: 0.1.1
homepage: https://github.com/y3l1n4ung/ease
repository: https://github.com/y3l1n4ung/ease

environment:
  sdk: '>=3.5.0 <4.0.0'
