name: ease_generator
description: Code generator for ease state management
version: 1.0.0
homepage: https://github.com/b14ckc0d3/ease
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  ease_annotation:
    path: ../ease_annotation
  build: ^4.0.3
  source_gen: ^4.1.1
  analyzer: ^8.1.1
  glob: ^2.1.3
  dart_style: ^3.1.2

dev_dependencies:
  test: ^1.24.0
  build_test: ^3.5.4
