name: ease_generator
description: Code generator for ease_state_helper Flutter state management library. Generates providers and context extensions from @Ease() annotations.
version: 0.1.2
homepage: https://github.com/y3l1n4ung/ease
repository: https://github.com/y3l1n4ung/ease
issue_tracker: https://github.com/y3l1n4ung/ease/issues

topics:
  - state-management
  - code-generation
  - build-runner

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  ease_annotation: ^0.1.2
  build: ^4.0.3
  source_gen: ^4.1.1
  analyzer: ^8.1.1
  glob: ^2.1.3
  dart_style: ^3.1.2

dev_dependencies:
  test: ^1.24.0
  build_test: ^3.5.4
