name: ease_devtools_extension
description: DevTools extension for ease_state_helper Flutter state management library. View and debug Ease states in Flutter DevTools.
version: 0.1.1
homepage: https://github.com/y3l1n4ung/ease
repository: https://github.com/y3l1n4ung/ease
issue_tracker: https://github.com/y3l1n4ung/ease/issues

topics:
  - state-management
  - flutter
  - devtools
  - debugging

environment:
  sdk: ^3.5.0
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.3.0
  ease_state_helper: ^0.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
